NAME: "BetterLineBreak"
MODRINTH_ID: "zp6DtFf2"
CURSEFORGE_ID: "960082"
CURSEFORGE_DEPENDENCIES: |
  cloth-config(required)
  modmenu(required)
MODRINTH_DEPENDENCIES: |
  cloth-config(required)
  modmenu(required)