# Publishes built jars to distribution platforms
name: Publish

on:
  workflow_dispatch:
    inputs:
      mod_platform:
        description: 'Mod platform'
        type: choice
        default: 'CurseForge and Modrinth and Github'
        options:
          - 'CurseForge and Modrinth and Github'
          - 'CurseForge'
          - 'Modrinth'
          - 'Github'
      commitish:
        description: 'Commit id'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # これが無いと正しくタグの存在を判定できない模様

      - name: Call workflow
        uses: KatatsumuriPan/KpansGitHubActions/.github/workflows/publish_base.yml@develop
        with:
          mod_platform: "${{ github.event.inputs.mod_platform }}"
          commitish: "${{ github.event.inputs.commitish }}"

